### ISSUE TITLE
Error: 1:2: 'filetree-open-files' 5:212: 'eval' 1:2: 'buffer' no such buffer 'p'

### ISSUE THREAD

**Issue by vbauerster** [occivink/kakoune-filetree#4]
I keep getting following error, while pressing enter on any file:
`Error: 1:2: 'filetree-open-files' 5:212: 'eval' 1:2: 'buffer' no such buffer 'p'`
Looks like, cause is latest commit...

**Comment by occivink** [comment]
What filename is causing this? I cannot reproduce, even with unusual filenames.

**Comment by vbauerster** [comment]
It happens inside tmux, when I split window with `:new` command. Pressing on any file results in this error.

**Comment by occivink** [comment]
Better now?

**Comment by vbauerster** [comment]
Yes, but buffer opens in different window now. Previous behaviour was to replace kak-filetree buffer.

**Comment by occivink** [comment]
Yes that is intentional, opening a buffer respects the `jumpclient` option, which indicates in which client jumps should be performed. This option is also used by `grep.kak`, `make.kak`...
I should probably also support `toolsclient` for opening the `*filetree*` buffer

**Comment by vbauerster** [comment]
I see now, thanks for fix and clarification, indeed I set `jumpclient` option recently in my config.
