### ISSUE TITLE
no such variable: source

### ISSUE THREAD

**Issue by xnuk** [occivink/kakoune-filetree#5]
```
$ kak -version
Kakoune v2022.10.31-245-ge3122ab2
```

Related: https://github.com/occivink/kakoune-filetree/blob/4c0c3147944e183be049fe98780a9a927455321e/filetree.kak#L1

So I couldn't guess what is `%val{source}` and what should I do (typing `: echo %val{source}` shows "Error: no such variable: source")

**Comment by occivink** [comment]
Hi,
normally `%val{source}` is set when the script is loaded using the `source` command. How did you load the script? I'm not sure why this would occcur

**Comment by xnuk** [comment]
> normally `%val{source}` is set when the script is loaded using the `source` command.

Did a quick debug right after reading this. It is a my fault, nevermind. My plugin script merged all the plugins I use into a single file, for increase little bit of startup speed, like:

```sh
fd --type=f -e kak . .config/kak/ -X cat > a-single-big-chunk.kak
echo source a-single-big-chunk.kak >> .config/kak/kakrc
```

**Comment by occivink** [comment]
well still, I would expect that since you do `source a-single-big-chunk.kak`, the value `source` still exists.
