### ISSUE TITLE
Failed to open file

### ISSUE THREAD

**Issue by wgaffa** [occivink/kakoune-filetree#7]
## Reproduce

- Open `:filetree`
- Press enter on a file

An error message `Unable to open 1 file` is shown.

I installed the plugin using bundle.

## Cause

The directory of the filetree command is stripped of **all** trailing "/" and once you press enter the plugin tries
to piece a path of all parents but the directory is missing a "/" to be able to produce a valid path. I believe this is why it can't open the file.

**Comment by occivink** [comment]
Can you paste the content of the buffer (or a minimal version of it)? I don't quite understand the description

**Comment by wgaffa** [comment]
```
.
├─── advent_of_code_2015/
│    ├─── 01/
│    │    ├─── input
│    │    ├─── part1.py
│    │    └─── part2.py
│    ├─── 02/
│    │    ├─── input
│    │    ├─── part1.py
│    │    └─── part2.py
```

Note that the top directory is missing a '/', if I change the kak script a little I can add it and then I can open files normally. I might supply a PR later on but not sure if the trailing slash should be added in the kak script or the perl script.

**Comment by occivink** [comment]
That's odd. Normally if you do `tree -p` (like in the script), the perl script should understand that the root is a directory and append the slash accordingly. 
For example in this directory, `tree -p` outputs
```
[drwxr-xr-x]  .
├── [-rw-r--r--]  filetree.kak
├── [-rw-r--r--]  filetree.perl
├── [-rw-r--r--]  README.md
├── [-rw-r--r--]  script
└── [-rw-r--r--]  UNLICENSE
```
and `tree -p | perl filetree.perl process` transforms it into
```
./
├─── filetree.kak
├─── filetree.perl
├─── README.md
├─── script
└─── UNLICENSE
```

**Comment by wgaffa** [comment]
```
.
├── [drwxr-xr-x]  advent_of_code_2015
│   ├── [drwxr-xr-x]  01
│   │   ├── [-rw-r--r--]  input
│   │   ├── [-rw-r--r--]  part1.py
│   │   └── [-rw-r--r--]  part2.py
│   ├── [drwxr-xr-x]  02
│   │   ├── [-rw-r--r--]  input
│   │   ├── [-rw-r--r--]  part1.py
│   │   └── [-rw-r--r--]  part2.py
```
It looks like I'm missing the chmod stuff on the top directory, could that be a problem?
The `tree --version` shows I'm using `1.8.0`, I tried looking what the latest version was but unable to find it.
I'm on WSL as well if that would cause some sort of issue as well.

What version of tree are you using?

**Comment by occivink** [comment]
>It looks like I'm missing the chmod stuff on the top directory, could that be a problem?

Definitely is the problem. The latest version seems to be [2.1.1](https://gitlab.com/OldManProgrammer/unix-tree/-/blob/master/CHANGES), though I don't see any changelog entry related to this. Try to upgrade if possible, and if not feel free to add local changes to handle this.

**Comment by wgaffa** [comment]
Yeah, I had a bit of a problem updating my distro in WSL2 but I managed to update it and tree is now at 2.1.0 and works fine.
